import React from "react";

function Blogs(props) {
  return (
    <div id="Resume">
      vocabulary
      vocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabulary
      vocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabulary
      vocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabulary
      vocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabularyvocabulary
    </div>
  );
}

export default Blogs;
